"""CAGE-JAX: JAX implementation of CAGE Challenge 2 environment."""

from jaxmarl.environments.cage.cage_env import CageEnv, make_cage_env
from jaxmarl.environments.cage.heuristic_red_cage_env import HeuristicRedCAGE
from jaxmarl.environments.cage.scripted_agents import (
    BLineState,
    bline_reset,
    bline_get_action,
    bline_reset_batched,
    bline_get_action_batched,
)
from jaxmarl.environments.cage.config import (
    ScenarioConfig,
    HostConfig,
    SubnetConfig,
    AgentConfig,
    create_scenario2_config,
    create_scalable_config,
    create_hosts_2_config,
    create_hosts_3_config,
    create_hosts_4_config,
    create_hosts_5_config,
    create_multi_agent_config,
    get_scenario,
    SCENARIOS,
)
from jaxmarl.environments.cage.state import (
    CageState,
    CageConst,
    create_scenario2_const,
    create_const_from_scenario,
    build_const_from_config,
    create_initial_state,
    create_initial_state_with_red_foothold,
    NUM_HOSTS,
    NUM_SUBNETS,
    NUM_SERVICES,
    NUM_EXPLOITS,
    NUM_DECOY_TYPES,
    HOST_IDS,
    HOST_NAMES,
    SUBNET_IDS,
    HOST_SUBNET,
    SERVICE_IDS,
    EXPLOIT_IDS,
    DECOY_IDS,
    COMPROMISE_NONE,
    COMPROMISE_USER,
    COMPROMISE_PRIVILEGED,
    OS_LINUX,
    OS_WINDOWS,
)

__all__ = [
    # Environment
    'CageEnv',
    'make_cage_env',
    'HeuristicRedCAGE',
    # Scripted agents
    'BLineState',
    'bline_reset',
    'bline_get_action',
    'bline_reset_batched',
    'bline_get_action_batched',
    # Configuration
    'ScenarioConfig',
    'HostConfig',
    'SubnetConfig',
    'AgentConfig',
    'create_scenario2_config',
    'create_scalable_config',
    'create_hosts_2_config',
    'create_hosts_3_config',
    'create_hosts_4_config',
    'create_hosts_5_config',
    'create_multi_agent_config',
    'get_scenario',
    'SCENARIOS',
    # State
    'CageState',
    'CageConst',
    'create_scenario2_const',
    'create_const_from_scenario',
    'build_const_from_config',
    'create_initial_state',
    'create_initial_state_with_red_foothold',
    # Constants (backward compatibility)
    'NUM_HOSTS',
    'NUM_SUBNETS',
    'NUM_SERVICES',
    'NUM_EXPLOITS',
    'NUM_DECOY_TYPES',
    'HOST_IDS',
    'HOST_NAMES',
    'SUBNET_IDS',
    'HOST_SUBNET',
    'SERVICE_IDS',
    'EXPLOIT_IDS',
    'DECOY_IDS',
    'COMPROMISE_NONE',
    'COMPROMISE_USER',
    'COMPROMISE_PRIVILEGED',
    'OS_LINUX',
    'OS_WINDOWS',
]
